### ISSUE TITLE
Add proxy support on HTTPD log access configurations

### ISSUE THREAD

**Issue by kms77** [fbaligand/lognavigator#1]
Presently, when we define a `log-access-config` typed `HTTPD`, we can't define a proxy to use to call the URL.

This would be nice to add the ability to define proxy host and proxy port to use to connect to HTTPD url.

**Comment by fbaligand** [comment]
In version 1.0.6, a new option has been added for that : `proxy`

Here is an example :
```
<log-access-config id="remote-httpd-logs" type="HTTPD" url="http://archive.apache.org/dist/tomcat/" proxy="proxy-host:proxy-port" />
```
