### ISSUE TITLE
Je cherche un dev passionné

### ISSUE THREAD

**Issue by jsmadja** [fbaligand/lognavigator#3]
Bonjour Fabien,

L'approche est un peu particulière mais je l'espère un peu plus originale.

Je suis Julien Smadja Consultant Manageur chez Xebia, on vous a déjà contacté par le passé (via Océane dernièrement).

Tout d’abord, je pense que je dois me présenter pour que tu saches qui t’écrit.

J’ai 34 ans, j’ai commencé ma carrière comme développeur Java en 2006 et j’ai intégré Xebia il y a un plus de 6 ans.
J’ai effectué différentes missions pour des clients et au bout de 3 ans, je suis passé Consultant Manageur.

Mais Manageur c’est un rôle que j’ai en plus, mon métier n’a pas changé et aujourd'hui j’ai un profil CTO Craftsmanship Javascript (Angular 2 et NodeJS sur Amazon WS).

J’ai maintenant 11 ans d’expérience et je suis toujours développeur.

Pourquoi je te contacte ? Au sein de Xebia nous cherchons à améliorer notre métier, nous pensons que nous nous devons d’être de meilleurs développeurs, de faire des projets plus maintenables, mieux écrits et d’en être fiers.

Je t'écris une issue sur un de tes projets personnels. J'aime cet esprit, je le partage aussi avec des projets opensource pour des associations et des communautés (plutôt orientées gaming que sociales). Je suis à la recherche de mes futurs collègues, des développeurs qui ont du vécu et du recul sur leur métier pour élever le niveau de notre profession. Est-ce que ce genre de défi t’intéresse ?

Je serais ravi d’en discuter avec toi.

Tu as peut-être envie d’en savoir plus sur moi via :

mon profil LinkedIn : https://www.linkedin.com/in/julien-smadja-46a56712a
mon compte Github : https://github.com/jsmadja
Dans l’attente de te lire,
Cordialement,

Julien

**Comment by fbaligand** [comment]
Bonjour Julien,

Merci pour ce contact quelque peu original, mais qui m'interpelle d'autant plus.
J'apprécie la démarche, et l'esprit que tu recherches. Je me reconnais bien dans cet esprit de chercher toujours à faire progresser notre métier, notre manière de travailler, et ainsi, gagner en efficacité, maintenabilité, collaboration et transparence.

Ceci étant dit, je ne suis pas aujourd'hui dans une démarche de recherche d'emploi.
Si cela était amené à évoluer, je n'hésiterais pas à te recontacter.

Fabien

**Comment by jsmadja** [comment]
Bonjour Fabien,

Content de voir que mon issue a été vue :) J'espère que si un jour tu poses des questions sur ton envie de changer tu repenseras à cette approche dans Github.

Je te souhaite une très bonne continuation

Julien

**Comment by fbaligand** [comment]
Bonne continuation à toi aussi.

Fabien
