### ISSUE TITLE
Tomcat 8.5 compliant

### ISSUE THREAD

**Issue by machette2612** [fbaligand/lognavigator#4]
Hello, 

Is your web application tomcat 8.5 compliant ?

Kind regards, 

Thomas

**Comment by fbaligand** [comment]
Hi,

I just tested LogNavigator on tomcat 8.5 and it works great !

**Comment by machette2612** [comment]
Hi, 

When I deploy your WAR in a tomcat8.5, I have the following error : 
type Rapport d''état

message /lognavigator/

description La ressource demandée n''est pas disponible.

which means that the application is not started. 

Port 8080 is opened and I can access to my tomcat management page.
Do you know which can be the root cause of this problem ?

Many thanks in advance for your answer, 

Best regards, 

Thomas

**Comment by fbaligand** [comment]
Strange...
Do you have some error logs in tomcat ? (catalina.out, catalina-<date>.log, ...)

**Comment by machette2612** [comment]
Yes, 

Some tips before: 
All the informations you need are in the logs (version of tomcat, openjdk, ...)
You need to know that the tomcat is running into a docker container, but it's change nothing to his real behaviour.
And here are the tomcat logs :
+ set -eo pipefail
+ catalina.sh version
Server version: Apache
Server built:   Feb 05 1901 19:20:44 UTC
Server number:  1-1-3-5-8-13-21
OS Name:        Linux
OS Version:     4.4.108-boot2docker
Architecture:   amd64
JVM Version:    1.8.0_151-b12
JVM Vendor:     Oracle Corporation
++ /bin/ls /usr/share/awl-tomcat8.5/deploy/
+ for file in '$(/bin/ls /usr/share/awl-tomcat8.5/deploy/)'
+ '[' -f /usr/share/awl-tomcat8.5/webapps/lognavigator.war ']'
+ '[' .war == .war ']'
+ ln -s /usr/share/awl-tomcat8.5/deploy/lognavigator.war /usr/share/awl-tomcat8.5/webapps/
+ exec /usr/share/awl-tomcat8.5/bin/catalina.sh run
23-Jan-2018 08:38:27.087 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:27.087 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:27.312 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:27.312 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:27.314 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:27.314 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:27.320 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:27.320 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:27.486 WARNING [main] org.apache.catalina.security.SecurityListener.checkUmask No umask setting was found in system property [org.apache.catalina.security.SecurityListener.UMASK]. However, it appears Tomcat is running on a platform that supports umask. The system property is typically set in CATALINA_HOME/bin/catalina.sh. The Lifecycle listener org.apache.catalina.security.SecurityListener (usually configured in CATALINA_BASE/conf/server.xml) expects a umask at least as restrictive as [0007]
23-Jan-2018 08:38:27.486 WARNING [main] org.apache.catalina.security.SecurityListener.checkUmask No umask setting was found in system property [org.apache.catalina.security.SecurityListener.UMASK]. However, it appears Tomcat is running on a platform that supports umask. The system property is typically set in CATALINA_HOME/bin/catalina.sh. The Lifecycle listener org.apache.catalina.security.SecurityListener (usually configured in CATALINA_BASE/conf/server.xml) expects a umask at least as restrictive as [0007]
23-Jan-2018 08:38:27.495 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache
23-Jan-2018 08:38:27.495 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Feb 05 1901 19:20:44 UTC
23-Jan-2018 08:38:27.495 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache
23-Jan-2018 08:38:27.495 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Feb 05 1901 19:20:44 UTC
23-Jan-2018 08:38:27.496 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         1-1-3-5-8-13-21
23-Jan-2018 08:38:27.497 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
23-Jan-2018 08:38:27.497 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.4.108-boot2docker
23-Jan-2018 08:38:27.497 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
23-Jan-2018 08:38:27.498 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.x86_64/jre
23-Jan-2018 08:38:27.498 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_151-b12
23-Jan-2018 08:38:27.498 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
23-Jan-2018 08:38:27.496 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         1-1-3-5-8-13-21
23-Jan-2018 08:38:27.499 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/share/awl-tomcat8.5
23-Jan-2018 08:38:27.497 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
23-Jan-2018 08:38:27.497 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.4.108-boot2docker
23-Jan-2018 08:38:27.497 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
23-Jan-2018 08:38:27.498 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.x86_64/jre
23-Jan-2018 08:38:27.498 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_151-b12
23-Jan-2018 08:38:27.498 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
23-Jan-2018 08:38:27.500 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/awl-tomcat8.5
23-Jan-2018 08:38:27.499 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/share/awl-tomcat8.5
23-Jan-2018 08:38:27.500 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/awl-tomcat8.5
23-Jan-2018 08:38:27.502 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/share/awl-tomcat8.5/conf/logging.properties
23-Jan-2018 08:38:27.502 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
23-Jan-2018 08:38:27.502 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
23-Jan-2018 08:38:27.503 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
23-Jan-2018 08:38:27.503 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.STRICT_SERVLET_COMPLIANCE=true
23-Jan-2018 08:38:27.502 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/share/awl-tomcat8.5/conf/logging.properties
23-Jan-2018 08:38:27.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.connector.RECYCLE_FACADES=true
23-Jan-2018 08:38:27.502 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
23-Jan-2018 08:38:27.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.coyote.USE_CUSTOM_STATUS_MSG_IN_HEADER=false
23-Jan-2018 08:38:27.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.connector.CoyoteAdapter.ALLOW_BACKSLASH=false
23-Jan-2018 08:38:27.502 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
23-Jan-2018 08:38:27.503 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
23-Jan-2018 08:38:27.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=false
23-Jan-2018 08:38:27.510 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dlognavigator.config=file:/usr/share/awl-tomcat8.5/conf/lognavigator.xml
23-Jan-2018 08:38:27.510 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
23-Jan-2018 08:38:27.503 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.STRICT_SERVLET_COMPLIANCE=true
23-Jan-2018 08:38:27.511 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/share/awl-tomcat8.5
23-Jan-2018 08:38:27.512 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/awl-tomcat8.5
23-Jan-2018 08:38:27.504 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.connector.RECYCLE_FACADES=true
23-Jan-2018 08:38:27.513 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/share/awl-tomcat8.5/temp
23-Jan-2018 08:38:27.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.coyote.USE_CUSTOM_STATUS_MSG_IN_HEADER=false
23-Jan-2018 08:38:27.513 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:27.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.connector.CoyoteAdapter.ALLOW_BACKSLASH=false
23-Jan-2018 08:38:27.505 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=false
23-Jan-2018 08:38:27.510 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dlognavigator.config=file:/usr/share/awl-tomcat8.5/conf/lognavigator.xml
23-Jan-2018 08:38:27.510 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
23-Jan-2018 08:38:27.511 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/share/awl-tomcat8.5
23-Jan-2018 08:38:27.512 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/awl-tomcat8.5
23-Jan-2018 08:38:27.513 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/share/awl-tomcat8.5/temp
23-Jan-2018 08:38:27.513 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:28.249 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:28.249 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:28.250 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
23-Jan-2018 08:38:28.250 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
23-Jan-2018 08:38:28.374 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
23-Jan-2018 08:38:28.374 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
23-Jan-2018 08:38:28.395 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:28.395 SEVERE [main] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14]
23-Jan-2018 08:38:28.400 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
23-Jan-2018 08:38:28.400 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
23-Jan-2018 08:38:28.419 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
23-Jan-2018 08:38:28.424 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 2997 ms
23-Jan-2018 08:38:28.419 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
23-Jan-2018 08:38:28.424 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 2997 ms
23-Jan-2018 08:38:28.516 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
23-Jan-2018 08:38:28.517 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache
23-Jan-2018 08:38:28.516 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
23-Jan-2018 08:38:28.517 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache
23-Jan-2018 08:38:28.639 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/share/awl-tomcat8.5/webapps/lognavigator.war]
23-Jan-2018 08:38:28.639 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/share/awl-tomcat8.5/webapps/lognavigator.war]
23-Jan-2018 08:38:33.211 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
23-Jan-2018 08:38:33.211 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
23-Jan-2018 08:38:33.226 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
23-Jan-2018 08:38:33.454 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
23-Jan-2018 08:39:08.446 WARNING [localhost-startStop-1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [33,148] milliseconds.
23-Jan-2018 08:39:08.446 WARNING [localhost-startStop-1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [33,148] milliseconds.
23-Jan-2018 08:39:08.522 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring FrameworkServlet 'lognavigator'
23-Jan-2018 08:39:10.138 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/share/awl-tomcat8.5/webapps/lognavigator.war] has finished in [41,499] ms
23-Jan-2018 08:39:10.138 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/share/awl-tomcat8.5/webapps/lognavigator.war] has finished in [41,499] ms
23-Jan-2018 08:39:10.151 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
23-Jan-2018 08:39:10.151 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
23-Jan-2018 08:39:10.167 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
23-Jan-2018 08:39:10.167 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
23-Jan-2018 08:39:10.174 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 41750 ms
23-Jan-2018 08:39:10.174 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 41750 ms
23-Jan-2018 08:39:10.318 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14] 23-Jan-2018 08:39:10.318 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.AprLifecycleListener.init An incompatible version [1.1.34] of the APR based Apache Tomcat Native library is installed, while Tomcat requires version [1.2.14] 127.0.0.1 - - [23/Jan/2018:08:39:10 +0000] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [23/Jan/2018:08:39:40 +0000] "GET / HTTP/1.1" 404 -
172.17.0.1 - - [23/Jan/2018:08:39:44 +0000] "GET /lognavigator/ HTTP/1.1" 404 997
172.17.0.1 - - [23/Jan/2018:08:39:44 +0000] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by fbaligand** [comment]
Strange to see you get absolutely no error log about LogNavigator deployment.
Usually, when you have a 404 error while accessing home page, it is because war deployment fails on tomcat.

In tomcat management app, do you see "lognavigator" ? Is the status "started" ?

Another thing is that LogNavigator app logs by default on standard console.
I don't see in your logs, any logs from LogNavigator app (using log4j pattern defined by LogNavigator app). Do you have standard console logs ?
By the way, you can customize log4j configuration, using java system property `"-Dlog4j.configuration=file:/path/to/log4j.properties"`

Finally, I notice in the log line below, that your java home is a JRE.
It is a problem for LogNavigator because it uses JSP technology that requires compilation (so a JDK)

Log line that indicates java home : 
`23-Jan-2018 08:38:27.498 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.151-1.b12.el7_4.x86_64/jre`

**Comment by machette2612** [comment]
The logs I shared to you is the standard console logs (by default, the container logs in stdout).
But I think it's more a JAVA_HOME problem. For the logging, we will manage to display something about lognav with log4j properties.

Many thanks for your quick answers.
I keep contact with you in case of others problems.

Best regards, 

Thomas

**Comment by fbaligand** [comment]
I also think that the current java_home value is your problem. 
Hope that it will solve your problem.
