### ISSUE TITLE
Cannot get tail to work

### ISSUE THREAD

**Issue by anaschillin** [fbaligand/lognavigator#7]
Hi,

I have deployed the app to tomcat in a linux envrioment.
Access the webpage in chrome on windows. 
When I hit run on default tail statement does not seem to work for me: 

- Default statement curl -ksS mpos-war.log | tail -1000

It seems to simply reload the page to the starting location.

**Comment by fbaligand** [comment]
Normally, it displays the last 1000 log lines.
If your log file contains less than 1000 lines, it always displays all file content.

**Comment by anaschillin** [comment]
Thanks...that would make sense
